### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vazhnov** [majianjia/QingStation#2]
Let's continue [this thread](https://hackaday.com/2021/07/06/open-source-ultrasonic-anemometer/#comment-6362287) here in Issues

> Source codes are under Apache-2.0. Only documentations and PCB are under CC. I can change them all in Apache 2.0 if CC-BY-NC is really concerning people. Yes, I am the author of QingStation.

**Comment by vazhnov** [comment]
Could you please update "Author & Copy Right" part of README, to mention Apache 2.0 license for a code?

**Comment by majianjia** [comment]
Hi @vazhnov , 
The firmware and bootloader are already under apache-2 in their own repos:
https://github.com/majianjia/QingStation-Firmware
https://github.com/majianjia/QingStation-bootloader
The CC license are meant for the documentation and PCB. 
Is this what you expected?

**Comment by vazhnov** [comment]
Yes! Thank you very much!
